---
#
# Installing Java 8
#

- name: Check if java8 is installed
  command: dpkg -l oracle-java8-installer
  register: deb_check
  ignore_errors: yes

- name: Add the Java repo
  apt_repository:
   repo: ppa:webupd8team/java
  failed_when: deb_check.stdout.find('Desired=Unknown/Install/Remove/Purge/Hold') != -1
  ignore_errors: yes
# Accept Oracle license

- name: Automatically accept the Oracle license
  shell: echo debconf shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections
  failed_when: deb_check.stdout.find('Desired=Unknown/Install/Remove/Purge/Hold') != -1
  ignore_errors: yes
# Install Java

- name: Install Java 8
  apt:
   name: oracle-java8-installer
   state: present
   update_cache: yes
  failed_when: deb_check.stdout.find('Desired=Unknown/Install/Remove/Purge/Hold') != -1
  ignore_errors: yes